#!/usr/bin/env python3
"""Regenerate SCRIPT.md from narration/lines.json and narration/timing.json.

SCRIPT.md is the human-readable locked narration. Generating it keeps it in
step with the line table and the timing the edit actually uses.
Run from the project root: python3 scripts/write-script-md.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
lines = json.loads((ROOT / "narration/lines.json").read_text(encoding="utf-8"))
timing = json.loads((ROOT / "narration/timing.json").read_text(encoding="utf-8"))
T = timing["lines"]
g = lines["engines"]["guide"]
e = lines["engines"]["elevenlabs"]
vs = e["voice_settings"]
pacing = lines["pacing"]
words = sum(len(l["text"].split()) for l in lines["lines"])

SECTION = {
    "b01": "Site wakes up (Frame 1)", "b02": "Insurance becomes workflow (Frames 1 and 2)",
    "b03": "Complexity outruns translation (Frame 1)", "b04": "Invisible crossing (Frame 1)",
    "b05": "Afterwards (Frames 1 and 3)", "b06": "Rewind (Frames 1 and 4)",
    "b07": "Speak the activity (Frame 4)", "b08": "Prevention and proof (Frame 4)",
    "b09": "Priora sees the change (Frame 5)", "b10": "Change, retain, transfer (Frame 5)",
    "b11": "Whole site and close (Frames 5 and 6)",
}

out = [
    "# SCRIPT: priora-vision-film",
    "",
    "Locked narration for the Priora vision film (Priora is the product, Valcorv the company). "
    "Generated by `scripts/write-script-md.py` from `narration/lines.json` (the machine source) and "
    "`narration/timing.json` (the authoritative word timings). Do not edit by hand.",
    "",
    "**Copy edits from the brief's script** (argument and claims unchanged; cut 2 removed the fixed 90 s "
    "runtime, so the voice runs at a natural pace on a 92 BPM grid): L05 'in mind'; "
    "L06 'hot work begins, every safeguard in place' (the certificate is named in L14b and shown on screen); "
    "L08 drops 'Work continues' (the drawing shows it); L14 split into L14a 'Priora connects the work to the "
    "conditions that matter.' and L14b 'It checks the certificate and safeguards, and keeps the record.' "
    "(L15 carries 'as it happens'); L16 'The sprinkler goes offline again. This time, Priora sees it at once.'; "
    "L17, split into L17a/b/c so each choice has room: 'The risk owner decides: change the work, knowingly "
    "retain the risk, or, in time, ask selected carriers whether they will cover it.' (carrier acceptance "
    "stays explicitly conditional).",
    "",
    "**Voice (final):** ElevenLabs, female, clear international British English (narrator); a natural male "
    "worker voice for L13. Route agreed with the user: the ElevenLabs web app in the agent's own browser. "
    "The API generator (`scripts/elevenlabs-voice.py`) exists but is not used without the user's approval.",
    f"**Voice settings (final):** model {e['model_id']} · stability {vs['stability']} · similarity "
    f"{vs['similarity_boost']} · style {vs['style']} · speaker boost {'on' if vs['use_speaker_boost'] else 'off'} · "
    "natural speed (1.0; never sped up or time-stretched). Per-line pace below mirrors the guide.",
    "**Voice direction:** Warm, intelligent, composed and credible. Calm authority without sounding "
    "aristocratic, theatrical, breathy, sentimental or like a commercial announcer. Natural conversational "
    "cadence with room around the condition failure, the rewind, the connection and the final chain. "
    "Underplay the vision: confidence comes from precision, not hype.",
    "**Worker direction:** A real worker on site speaking into a phone. Natural, practical, close-mic. Not an "
    "actor performing a slogan.",
    f"**Guide voice (build only, not final):** local Kokoro {g['narrator_voice']} (narrator) and "
    f"{g['worker_voice']} (worker), narrator speed {g['narrator_speed']} with per-line pace.",
    "**Pronunciation:** Priora is pree-OH-ruh (IPA pɹiˈəʊɹə), stress on the middle syllable, never PRY-ora. "
    "ElevenLabs text uses the respelling `Pree-OH-ruh`. Roof 03 is said Roof oh-three.",
    f"**Pacing:** lead-in {pacing['lead_in']} s, designed silence after each line as listed, "
    f"rewind silence {timing['rewind']['end'] - timing['rewind']['start']:.2f} s before L12, end hold "
    f"{pacing['end_hold']} s. Total {timing['duration_total']:.2f} s, {words} words.",
    "",
    "**Time** values are from the current assembly (engine: " + timing["engine"] + "). After the ElevenLabs "
    "take is assembled, `narration/timing.json` is the truth.",
    "",
    "---",
    "",
]
for n, l in enumerate(lines["lines"], 1):
    t = T[l["id"]]
    sec = SECTION.get(l.get("section", "")[:3], l.get("section", ""))
    out += [f"## Line {n} ({l['id']}): {sec}", ""]
    out.append(f"**Speaker:** {'Worker' if l['speaker'] == 'worker' else 'Narrator'}  ")
    out.append(f"**Time:** {t['start']:.2f} to {t['end']:.2f} s ({timing['engine']})  ")
    if l.get("delivery"):
        out.append(f"**Delivery:** {l['delivery']}  ")
    if l.get("pace", 1.0) != 1.0:
        out.append(f"**Pace:** {l['pace']} of the global speed  ")
    if l.get("pre_gap"):
        out.append(f"**Silence before:** {l['pre_gap']} s (rewind)  ")
    out.append(f"**Silence after:** {l.get('gap_after', 0)} s  ")
    tt = l.get("tts_text") or {}
    if tt.get("elevenlabs") and tt["elevenlabs"] != l["text"]:
        out.append(f"**Spoken as (ElevenLabs):** `{tt['elevenlabs']}`  ")
    out += ["", "    " + l["text"], ""]
(ROOT / "SCRIPT.md").write_text("\n".join(out), encoding="utf-8")
print(f"SCRIPT.md written: {len(lines['lines'])} lines, {words} words, {timing['duration_total']:.2f} s")
